All environments registered in gym:

In [2]:
from gym import envs
print(envs.registry.all())

dict_values([EnvSpec(Copy-v0), EnvSpec(RepeatCopy-v0), EnvSpec(ReversedAddition-v0), EnvSpec(ReversedAddition3-v0), EnvSpec(DuplicatedInput-v0), EnvSpec(Reverse-v0), EnvSpec(CartPole-v0), EnvSpec(CartPole-v1), EnvSpec(MountainCar-v0), EnvSpec(MountainCarContinuous-v0), EnvSpec(Pendulum-v0), EnvSpec(Acrobot-v1), EnvSpec(LunarLander-v2), EnvSpec(LunarLanderContinuous-v2), EnvSpec(BipedalWalker-v3), EnvSpec(BipedalWalkerHardcore-v3), EnvSpec(CarRacing-v0), EnvSpec(Blackjack-v0), EnvSpec(KellyCoinflip-v0), EnvSpec(KellyCoinflipGeneralized-v0), EnvSpec(FrozenLake-v0), EnvSpec(FrozenLake8x8-v0), EnvSpec(CliffWalking-v0), EnvSpec(NChain-v0), EnvSpec(Roulette-v0), EnvSpec(Taxi-v3), EnvSpec(GuessingGame-v0), EnvSpec(HotterColder-v0), EnvSpec(Reacher-v2), EnvSpec(Pusher-v2), EnvSpec(Thrower-v2), EnvSpec(Striker-v2), EnvSpec(InvertedPendulum-v2), EnvSpec(InvertedDoublePendulum-v2), EnvSpec(HalfCheetah-v2), EnvSpec(HalfCheetah-v3), EnvSpec(Hopper-v2), EnvSpec(Hopper-v3), EnvSpec(Swimmer-v2), EnvSp

# CartPole-v1 Environment Introduction
Link: 

https://gym.openai.com/envs/CartPole-v1/

https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py

A pole is attached by an un-actuated joint to a cart, which moves along a frictionless track. The system is controlled by applying a force of +1 or -1 to the cart. The pendulum starts upright, and the goal is to prevent it from falling over. A reward of +1 is provided for every timestep that the pole remains upright. The episode ends when the pole is more than 15 degrees from vertical, or the cart moves more than 2.4 units from the center.

In [3]:
# Simple Visualization
import gym

env = gym.make('CartPole-v1')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[ 0.00449268 -0.0400185  -0.01197678  0.03391883]
[ 0.00369231 -0.23496667 -0.0112984   0.32279903]
[-0.00100703 -0.03968567 -0.00484242  0.02657456]
[-0.00180074 -0.23473784 -0.00431093  0.31772572]
[-0.0064955  -0.03955475  0.00204358  0.02368641]
[-0.00728659 -0.23470595  0.00251731  0.31701341]
[-0.01198071 -0.42986367  0.00885758  0.61048914]
[-0.02057798 -0.23486664  0.02106736  0.32060916]
[-0.02527532 -0.43028218  0.02747954  0.61986078]
[-0.03388096 -0.62577693  0.03987676  0.92107016]
[-0.0463965  -0.43121589  0.05829816  0.64118127]
[-0.05502082 -0.62710001  0.07112179  0.95163822]
[-0.06756282 -0.8231033   0.09015455  1.26579208]
[-0.08402488 -0.62924155  0.11547039  1.00264996]
[-0.09660971 -0.43583579  0.13552339  0.74834614]
[-0.10532643 -0.63254108  0.15049032  1.08042064]
[-0.11797725 -0.82929451  0.17209873  1.41629248]
[-0.13456314 -1.02607876  0.20042458  1.757456  ]
Episode finished after 18 timesteps
[0.01668442 0.00706628 0.00928444 0.0478845 ]
[ 0.01682575  0.20

[-0.0316576  -0.62122583  0.15863806  1.11731948]
[-0.04408212 -0.42850051  0.18098445  0.87830571]
[-0.05265213 -0.23623816  0.19855057  0.64754194]
Episode finished after 14 timesteps
[ 0.04582543  0.02940216  0.03863221 -0.03960083]
[ 0.04641348  0.22394944  0.03784019 -0.31984897]
[ 0.05089247  0.02830959  0.03144321 -0.01547691]
[ 0.05145866  0.22296682  0.03113368 -0.29807565]
[ 0.05591799  0.41763146  0.02517216 -0.58077927]
[ 0.06427062  0.61239181  0.01355658 -0.86542742]
[ 0.07651846  0.80732665 -0.00375197 -1.15381729]
[ 0.09266499  0.61225383 -0.02682832 -0.86231321]
[ 0.10491007  0.41750725 -0.04407458 -0.57818503]
[ 0.11326021  0.22302983 -0.05563828 -0.29970593]
[ 0.11772081  0.41889887 -0.0616324  -0.60940408]
[ 0.12609879  0.61482578 -0.07382048 -0.9208449 ]
[ 0.1383953   0.81086355 -0.09223738 -1.23578419]
[ 0.15461257  0.61704001 -0.11695306 -0.97336411]
[ 0.16695337  0.42366488 -0.13642035 -0.71958877]
[ 0.17542667  0.2306677  -0.15081212 -0.47276595]
[ 0.18004003  

[ 0.10357374  0.16952181 -0.13389522 -0.34272962]
[ 0.10696417  0.36626929 -0.14074981 -0.67445701]
[ 0.11428956  0.56303764 -0.15423895 -1.00793475]
[ 0.12555031  0.37027341 -0.17439765 -0.76738761]
[ 0.13295578  0.56731231 -0.1897454  -1.1094761 ]
Episode finished after 18 timesteps
[-0.01810662 -0.02791121  0.00999222 -0.02520615]
[-0.01866484 -0.22317502  0.0094881   0.27061261]
[-0.02312834 -0.02818974  0.01490035 -0.01906268]
[-0.02369214 -0.22352218  0.0145191   0.27828398]
[-0.02816258 -0.02861033  0.02008478 -0.00978451]
[-0.02873479  0.1662179   0.01988909 -0.29606339]
[-0.02541043 -0.02918186  0.01396782  0.00282529]
[-0.02599407  0.16573702  0.01402432 -0.2854181 ]
[-0.02267933 -0.02958211  0.00831596  0.0116548 ]
[-0.02327097 -0.22482233  0.00854906  0.30694986]
[-0.02776741 -0.02982323  0.01468806  0.0169753 ]
[-0.02836388  0.16508503  0.01502756 -0.27103742]
[-0.02506218 -0.0302481   0.00960681  0.02634713]
[-0.02566714  0.16473477  0.01013376 -0.26328932]
[-0.02237244 -

## CartPole-v1 environment details

(From https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py)


- Description:

    A pole is attached by an un-actuated joint to a cart, which moves along
    a frictionless track. The pendulum starts upright, and the goal is to
    prevent it from falling over by increasing and reducing the cart's
    velocity.
    

- Observation:

        Type: Box(4)
        Num   Observation               Min             Max
        0     Cart Position             -4.8            4.8
        1     Cart Velocity             -Inf            Inf
        2     Pole Angle                -24 deg         24 deg
        3     Pole Velocity At Tip      -Inf            Inf

- Actions:

        Type: Discrete(2)
        Num   Action
        0     Push cart to the left
        1     Push cart to the right

    Note: The amount the velocity that is reduced or increased is not
    fixed; it depends on the angle the pole is pointing. This is because
    the center of gravity of the pole increases the amount of energy needed
    to move the cart underneath it


- Reward:

    Reward is 1 for every step taken, including the termination step


- Starting State:

    All observations are assigned a uniform random value in [-0.05,0.05]


- **Episode Termination**:

    - Pole Angle is more than **12 degrees (around 0.209 rad)**.

    - Cart Position is more than **2.4** (center of the cart reaches the edge of the display). 
    
    - Episode length is greater than 200.


- Solved Requirements:

    Considered solved when the average reward is greater than or equal to 195.0 over 100 consecutive trials.


### Physical Parameters Initialization

    self.gravity = 9.8  
    self.masscart = 1.0  
    self.masspole = 0.1  
    self.total_mass = (self.masspole + self.masscart)  
    self.length = 0.5  # actually half the pole's length  
    self.polemass_length = (self.masspole * self.length)    
    self.force_mag = 10.0  # The force appilied to the cart in an action(0->-10, 1->10)  
    self.tau = 0.02  # seconds between state updates  
    self.kinematics_integrator = 'euler'  

    #### Angle at which to fail the episode
    self.theta_threshold_radians = 12 * 2 * math.pi / 360       # 12 degree = 0.209 rad  
    self.x_threshold = 2.4  

    #### Angle limit set to 2 * theta_threshold_radians so failing observation is still within bounds.
    high = np.array([self.x_threshold * 2,
                     np.finfo(np.float32).max,
                     self.theta_threshold_radians * 2,
                     np.finfo(np.float32).max],
                    dtype=np.float32)  

    ( [4.8, inf, 24degree, inf])    

    self.action_space = spaces.Discrete(2)  
    self.observation_space = spaces.Box(-high, high, dtype=np.float32)  
    self.seed()  
    self.viewer = None  
    self.state = None  
    self.steps_beyond_done = None  

In [4]:
# Check
print(env.action_space)
print(env.observation_space)
print(env.observation_space.high)
print(env.observation_space.low)

Discrete(2)
Box(4,)
[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


### Motion Model


---

$$
\ddot{\theta} = \frac{(M+m)g sin\theta - cos\theta[F+ml\dot{\theta}^2sin\theta]}{\frac{4}{3}(M+m)l - m l cos^2\theta}
$$
$$
\ddot{p} = \frac{F+ml[\dot{\theta}^2 sin\theta - \ddot{\theta} cos\theta]}{M+m}
$$

Where $\theta$ and $\dot{\theta}$ is the angular position and velocity of pendulum, $p$ and $\dot{p}$ is the position and velocity of cart, $M$ is the mass of cart, $m$ is the mass of pendulum, $g$ is gravitational acceleration, $F$ is the force applied to the cart, $l$ is the length from the center of mass to the pivot.

---


    x, x_dot, theta, theta_dot = self.state  
    force = self.force_mag if action == 1 else -self.force_mag  
    costheta = math.cos(theta)  
    sintheta = math.sin(theta)  

#For the interested reader:  
#https://coneural.org/florian/papers/05_cart_pole.pdf  

    temp = (force + self.polemass_length * theta_dot ** 2 * sintheta) / self.total_mass
    thetaacc = (self.gravity * sintheta - costheta * temp) / (self.length * (4.0 / 3.0 - self.masspole * costheta ** 2 / self.total_mass))
    xacc = temp - self.polemass_length * thetaacc * costheta / self.total_mass

    if self.kinematics_integrator == 'euler': # By default   
        x = x + self.tau * x_dot  
        x_dot = x_dot + self.tau * xacc  
        theta = theta + self.tau * theta_dot  
        theta_dot = theta_dot + self.tau * thetaacc  
    else:  # semi-implicit euler  
        x_dot = x_dot + self.tau * xacc  
        x = x + self.tau * x_dot  
        theta_dot = theta_dot + self.tau * thetaacc  
        theta = theta + self.tau * theta_dot  
  
    self.state = (x, x_dot, theta, theta_dot)  

### Episode Termination
---
    done = bool(
                x < -self.x_threshold
                or x > self.x_threshold
                or theta < -self.theta_threshold_radians
                or theta > self.theta_threshold_radians
            )

### Reward
--- 
    if not done:  # Not reach Termination
        reward = 1.0
    elif self.steps_beyond_done is None:
        # Pole just fell!
        self.steps_beyond_done = 0
        reward = 1.0
    else:
        if self.steps_beyond_done == 0:
            logger.warn(
                "You are calling 'step()' even though this "
                "environment has already returned done = True. You "
                "should always call 'reset()' once you receive 'done = "
                "True' -- any further steps are undefined behavior."
            )
        self.steps_beyond_done += 1
        reward = 0.0

### Reset 
--- 
    def reset(self):
            self.state = self.np_random.uniform(low=-0.05, high=0.05, size=(4,))
            self.steps_beyond_done = None
            return np.array(self.state)

In [7]:
print(env.action_space)
# print(env.observation_space)
# print(env.observation_space.high)
# print(env.observation_space.low)

Discrete(2)


In [1]:
import gym
import numpy as np
all_observation = np.array([0,0,0,0])

env = gym.make('CartPole-v1')


for i_episode in range(50):
    observation = env.reset()
    for t in range(200):
        env.render()
#         print(observation)
        all_observation = np.vstack((all_observation, observation))
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

Episode finished after 20 timesteps
Episode finished after 72 timesteps
Episode finished after 21 timesteps
Episode finished after 11 timesteps
Episode finished after 20 timesteps
Episode finished after 11 timesteps
Episode finished after 19 timesteps
Episode finished after 18 timesteps
Episode finished after 33 timesteps
Episode finished after 25 timesteps
Episode finished after 38 timesteps
Episode finished after 27 timesteps
Episode finished after 25 timesteps
Episode finished after 30 timesteps
Episode finished after 14 timesteps
Episode finished after 12 timesteps
Episode finished after 21 timesteps
Episode finished after 29 timesteps
Episode finished after 17 timesteps
Episode finished after 12 timesteps
Episode finished after 19 timesteps
Episode finished after 41 timesteps
Episode finished after 20 timesteps
Episode finished after 27 timesteps
Episode finished after 33 timesteps
Episode finished after 14 timesteps
Episode finished after 17 timesteps
Episode finished after 27 ti

In [17]:
print(env.observation_space.high)
print(env.observation_space.low)
print(all_observation.shape)
print(np.max(all_observation, axis = 0))
print(np.min(all_observation, axis = 0))


[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]
(471, 4)
[0.21673986 1.55362511 0.20883955 2.34863741]
[-0.17247946 -1.56646328 -0.20826308 -2.37250619]


In [2]:
type(env.observation_space.high)

numpy.ndarray